### ISSUE TITLE
Publishing to HuggingFace Models?

### ISSUE THREAD

**Issue by OElesin** [salesforce/CodeT5#1]

**Comment by Alexmhack** [comment]
Yes that would be great, even if the pre-trained weights and code is open sourced, noobs like me will take a lot of time to figure out how to put CodeT5 to actual use in production or as a service.

**Comment by yuewang-cuhk** [comment]
Hi folks, thanks for the advice. Yes, we are in the process of putting CodeT5 models to Huggingface. Please stay tuned.

**Comment by yuewang-cuhk** [comment]
Hi folks, we have released CodeT5 models on Hugging Face: [CodeT5-small](https://huggingface.co/Salesforce/codet5-small) and [CodeT5-base](https://huggingface.co/Salesforce/codet5-base)!

**Comment by OElesin** [comment]
YEAY!!!

**Comment by OElesin** [comment]
@yuewang-cuhk , can you please add some example usage, as well as fine-tuning the model on custom dataset?

Thanks a lot for this already.

**Comment by saikat107** [comment]
Are these models all trained with "multi-task"?
