### ISSUE TITLE
Defect detection model setup: unigram generation or embedding classification?

### ISSUE THREAD

**Issue by MayankAgarwal** [salesforce/CodeT5#107]
Hi CodeT5 authors,

Thank you for providing the code and models for your papers. They have been extremely useful.

I am trying the defect detection pipeline and noticed that in the paper it is mentioned that you generate a unigram sequence from the decoder ([page 8, under table 6](https://arxiv.org/pdf/2109.00859.pdf)) while in the code the Defect Model ([Code Link](https://github.com/salesforce/CodeT5/blob/main/CodeT5/models.py#L123)) trains a classifier on top of decoder hidden states for CodeT5 and other models as well. From what I understand, the paper suggests that you formulated this problem as seq2seq task with code as input and a yes/no or true/false output as unigram sequence.

Could you please clarify which approach did you take for this task?

Thanks!

**Comment by yuewang-cuhk** [comment]
Hi there, in fact both ways are able to achieve good results on the defect detection task. For our original CodeT5 paper, we experimented with both ways and decided to adopt the way of unigram generation to make it into a unified seq2seq format. For CodeT5+, we use the embedding classification way as it has a flexible encoder-only mode to support this task. Hope this can clarify your confusions.

**Comment by MayankAgarwal** [comment]
Thank you! This was really helpful
