### ISSUE TITLE
Is it possible for us to fine-tune codeT5+?

### ISSUE THREAD

**Issue by liangyingshao** [salesforce/CodeT5#109]

**Comment by antonio-mastropaolo** [comment]
I was wondering the same!
Have you managed to find a solution?

**Comment by yuewang-cuhk** [comment]
Hi there, please refer to [here](https://github.com/salesforce/CodeT5/tree/main/CodeT5%2B#how-to-finetune-using-your-own-data) for how to finetune CodeT5+ using on own data.
