### ISSUE TITLE
About  AI coding assistant demo

### ISSUE THREAD

**Issue by skye95git** [salesforce/CodeT5#11]
Hi, the newly added `AI coding assistant demo` is cool! I have a few questions about it:

1. Did you make the codeT5 model into VS Code plugin? How did you do that?

2. When demonstrating code generation, editing the comment generates the corresponding code snippet. Aren't the inputs to the code generation model natural Language Description and class Environment? 
<img width="814" alt="捕获" src="https://user-images.githubusercontent.com/41561936/136541417-3b273945-aa1a-44e8-a9e4-f440770734e6.PNG">

The format of the data in the Concode dataset is
```json
{
    "code": "int function ( double [ ] arg0 , double [ ] arg1 ) { int loc0 = arg0 . length - arg1 . length ; outer : for ( int loc1 = 0 ; loc1 <= loc0 ; loc1 ++ ) { for ( int loc2 = 0 ; loc2 < arg1 . length ; loc2 ++ ) { if ( ne ( arg0 [ loc1 + loc2 ] , arg1 [ loc2 ] ) ) { continue outer ; } } return ( loc1 ) ; } return ( - 1 ) ; }",
    "nl": "searches for the first subsequence of a that matches sub elementwise . elements of sub are considered to match elements of a if they pass the #eq test . concode_field_sep double max_ratio concode_elem_sep double min_ratio concode_elem_sep boolean off concode_field_sep boolean isElemMatch concode_elem_sep int compare concode_elem_sep boolean isSubset concode_elem_sep boolean ne concode_elem_sep boolean lt concode_elem_sep boolean gte concode_elem_sep void set_rel_diff concode_elem_sep boolean eq concode_elem_sep boolean lte concode_elem_sep boolean gt"
}
```

Is it possible to generate accurate code snippet by typing only comments without class Environment? Doesn't the loss of context information affect the quality of the generated code?

**Comment by yuewang-cuhk** [comment]
Hey there, 

Yes, I make a CodeT5 demo as a VS code plugin. We first run the model on the GCP and expose it as a web service, which is then integrated into the VS Code extension. Please refer to this [online tutorial](https://youtu.be/LK5G1kSU0Ms) for more details.

For the demo of code generation, the source input is only the natural language description. We fine-tune another  CodeT5 model for this on our customized Apex dataset, which is not the Concode data and has no env variables.
