### ISSUE TITLE
can you provide requirements.txt?

### ISSUE THREAD

**Issue by dsp6414** [salesforce/CodeT5#121]
pls help me, where can i find the file "requirements.txt"?

**Comment by dsp6414** [comment]
☘️

**Comment by armandmousavi** [comment]
I would move to reopen this since it could still be useful for performing something like finetuning in the future.

**Comment by dsp6414** [comment]
已收到！

**Comment by CarlChang39** [comment]
您好，请问可以发给我一份吗，多谢
