### ISSUE TITLE
Could you share the script of how to fine-tune CodeT5p with instruction dataset?

### ISSUE THREAD

**Issue by Cxm211** [salesforce/CodeT5#123]
I have difficulty using my own instruction dataset to fine-tune CodeT5p. Could you please share your script of instruction-tuning? Thank you very much!

**Comment by yuewang-cuhk** [comment]
Hi, we have released the instruction tuning script. Please refer to [here](https://github.com/salesforce/CodeT5/tree/main/CodeT5%2B#instruction-tuning-to-align-with-natural-language-instructions) for more details. Thanks:)
