### ISSUE TITLE
Is the decoder of large CodeT5p fine-tuned during the fine-tuning ?

### ISSUE THREAD

**Issue by huynhvp** [salesforce/CodeT5#125]
Hello, 

Thank you for the great work ! I am wondering if the decoder will be fine-tuned or still be kept intact during the fine-tuning with my own training dataset, as during the pretraning, it is freezed.

Thank you for your answer !

**Comment by yuewang-cuhk** [comment]
Hi there, you can decide whether to finetune the deep decode LLM by commenting/uncommenting this [line](https://github.com/salesforce/CodeT5/blob/a1215960ef8696addad1a08b984e87ad8eab88cf/CodeT5%2B/instruct_tune_codet5p.py#L177).
