### ISSUE TITLE
Code summarization example

### ISSUE THREAD

**Issue by JaktensTid** [salesforce/CodeT5#126]
Hi, is there any example of a code summarization? 
Thank you in advance!

**Comment by JaktensTid** [comment]
Hi @yuewang-cuhk, thank you for your help!
I help another question - is this possible to give an entire class or group of classes instead of single function so model can 'catch up' context more precisely, or I must fine-tune it for this task?

**Comment by yuewang-cuhk** [comment]
The model should be also able to summarize a larger code patch to some extent. But as it is trained using code-text pairs at the function level, finetuning it on your new use case would be definitely better.
