### ISSUE TITLE
Pre-training dataset

### ISSUE THREAD

**Issue by mciniselli** [salesforce/CodeT5#13]
Hi, 
thank you for this amazing model!
I was wondering if you can share with us the 8.3M methods dataset used for the pretraining.

Thank you very much!
Matteo

**Comment by yuewang-cuhk** [comment]
Hi, thanks for your interest! We are still in the process to resolve the potential risks of releasing the extra C/C# data collected from BigQuery. For the CodeSearchNet data, we employ all non-valid/test examples for pre-training CodeT5. You can access this data from its official [repo](https://github.com/github/CodeSearchNet).

**Comment by ShushanArakelyan** [comment]
Hi, could you please clarify on the dataset you use for pretaining? Does "all non-valid/test examples from CodeSearchNet" mean examples from the training portion of the dataset? 

For example, for Python, I counted only 412178 such examples in CodeSearchNet, but in the paper, you mention you used 453,772 Python examples for pretraining from CodeSearchNet.
