### ISSUE TITLE
Prediction on new data

### ISSUE THREAD

**Issue by surtantheta** [salesforce/CodeT5#14]
Can you provide a small instance of CodeT5's prediction on concode data set for the concode task ? I am not sure how to make predictions on new data and what command line argument to use.

**Comment by yuewang-cuhk** [comment]
Hi, for fine-tuning CodeT5-base on the concode task, you can go to `sh` folder and simply type `python run_exp.py --model_tag codet5_base --task concode --sub_task none`.

If you want to fine-tune on your dataset, you can add your own task in `configs.py` ([here](https://github.com/salesforce/CodeT5/blob/d27512d23ba6130e089e571d8c3e399760db1c31/configs.py#L11)) and add your data path and the function to read in `utils.py` ([here](https://github.com/salesforce/CodeT5/blob/5bb41e21b07fee73f310476a91ded00e385290d7/utils.py#L103) and [here](https://github.com/salesforce/CodeT5/blob/5bb41e21b07fee73f310476a91ded00e385290d7/utils.py#L149)). The read function can be implemented in `_utils.py` similar to [this one](https://github.com/salesforce/CodeT5/blob/aaf9c4a920c4986abfd54a74f5456b056b6409e0/_utils.py#L213).
