### ISSUE TITLE
Does CodeT5 continue pre-training based on T5?

### ISSUE THREAD

**Issue by BitcoinNLPer** [salesforce/CodeT5#18]
Does CodeT5 continue pre-training based on origin T5? Or did you only use the T5 architecture without using the T5 weights and conduct training from scratch?

Thanks!

**Comment by yuewang-cuhk** [comment]
Hi, we pre-train CodeT5 from scratch on code as we build our own code-specific tokenizer and cannot leverage the T5 weights. You can find such information in the paper:)

**Comment by BitcoinNLPer** [comment]
Thank u!
