### ISSUE TITLE
Make exp_with_args.sh runnable by any user

### ISSUE THREAD

**Issue by klavinski** [salesforce/CodeT5#2]
The user `wang.y` is hard-coded into `sh/exp_with_args.sh`. It would be great if one could just clone the repository, install the dependencies, and run `exp_with_args.sh`.

**Comment by yuewang-sf** [comment]
Hi @klavinski, thanks for the advice! We have improved the scripts accordingly. You just need to revise the following line into your downloaded CodeT5 path:
https://github.com/salesforce/CodeT5/blob/100c7e55c1e120600a2e114e828a157d265a2411/sh/exp_with_args.sh#L1
