### ISSUE TITLE
Can the CodeT5 model do code autocompletion without fine-tuning?

### ISSUE THREAD

**Issue by frankxu2004** [salesforce/CodeT5#21]
The readme mentioned that this is used for Code autocompletion in VSCode, I wonder how to use CodeT5 without fine-tuning as a language model to complete code given some previous context in code?

**Comment by yuewang-cuhk** [comment]
Yes, it can support this for completing a code span. Generally, CodeT5 without fine-tuning would be more suitable for code span autocompletion with previous and after contexts, which is more aligned with span denoising objective in pre-training.

**Comment by frankxu2004** [comment]
Thanks for the quick response. I wonder how long (say the number of tokens) the code span completion usually is?

**Comment by yuewang-cuhk** [comment]
We have included such details in the paper: the average of span length is 3 tokens (before subword tokenization).
