### ISSUE TITLE
Is it possible to finetune codet5 with the programming language which is not a part of codesearchnet dataset. 

### ISSUE THREAD

**Issue by likhith00** [salesforce/CodeT5#22]
If it is not possible is pretraining codet5 with that new programming language dataset the only option?

**Comment by yuewang-cuhk** [comment]
Hi, it is possible that fine-tuning CodeT5 on a new programming language (PL) would achieve a reasonable result, as different PLs might share some common patterns and this allows transfer learning to another PL. For example, we find that fine-tuning CodeT5 on Apex yields good results (as shown in the [GIF animation](https://github.com/salesforce/CodeT5/blob/main/codet5.gif)) as it is very similar to Java.
