### ISSUE TITLE
Multi-task models

### ISSUE THREAD

**Issue by Otavio-Parraga** [salesforce/CodeT5#25]
Dear authors,

First, congrats on the amazing paper!

In the paper, you train models in downstream tasks with a multi-task learning approach. When I went into the available models, I could not find the ones fine-tuned with multi-task learning. I also could not find the scripts for it, but I saw in Issue #7  that you are already planning to release them.

**In summary, my question is: There are any plans to release the multi-task models?**

Thanks in advance for your clarification!

**Comment by yuewang-cuhk** [comment]
Hi, we do not plan to release the multi-task models. Note that as we allow to select different best checkpoints for different tasks, there is no one best unifed model for all the tasks. The multi-task training script is released at [here](https://github.com/salesforce/CodeT5/blob/main/run_multi_gen.py). Now you can type the below command to trigger the multi-task training:


```
python run_exp.py --model_tag codet5_base --task multi_task --sub_task none
```
