### ISSUE TITLE
finetuned checkpoints

### ISSUE THREAD

**Issue by saichandrapandraju** [salesforce/CodeT5#3]
Hi,
Is there any plan to release the finetuned checkpoints?

**Comment by pocca2048** [comment]
Do you mean this?
https://drive.google.com/drive/folders/1djlsk7ED8agTyWUe0aWeAbxIR5pzSvVo?usp=sharing

**Comment by saichandrapandraju** [comment]
Hi @pocca2048 ,

Thanks for your reply. 

What I meant was fine-tuned weights for CodeXGlue tasks that were reported in the paper.

**Comment by yuewang-cuhk** [comment]
> Hi @pocca2048 ,
> 
> Thanks for your reply.
> 
> What I meant was fine-tuned weights for CodeXGlue tasks that were reported in the paper.

Hi @saichandrapandraju, yes, we plan to release some fine-tuned checkpoints soon. Please stay tuned:)

**Comment by yuewang-cuhk** [comment]
Hi there, we have released fine-tuned CodeT5-base checkpoints for all downstream tasks [here](https://console.cloud.google.com/storage/browser/sfr-codet5-data-research/finetuned_models)!
