### ISSUE TITLE
Which tokenizer to use for customized python summary data?

### ISSUE THREAD

**Issue by blurLake** [salesforce/CodeT5#30]
Hi, 
I am fine-tuning codeT5 base model.  I see in exp_with_args.sh that for python summarization task, RobertaTokenizer is used. However, in the data you shared in [here](https://console.cloud.google.com/storage/browser/sfr-codet5-data-research/data/summarize/python?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) does not look like to be generated by RobertaTokenizer. Since Robertatokenizer will tokenize space as Ġ, see e.g.. [here](https://github.com/huggingface/transformers/issues/4786), but in the data you uploaded, there is no such Ġ in code_token, nor in string_token. 

Could you comment on this? Thank you very much!

**Comment by yuewang-cuhk** [comment]
Hi, the shared data is the raw data that will be tokenized by our code-specific RobertaTokenizer (not the original one). We use this [function](https://github.com/salesforce/CodeT5/blob/34a6310f9604f77031b6a412a1b2b3873dbd6e19/_utils.py#L233) to read summarization data and this unified tokenizing [function](https://github.com/salesforce/CodeT5/blob/34a6310f9604f77031b6a412a1b2b3873dbd6e19/_utils.py#L21) to convert it to features.
