### ISSUE TITLE
How to use fine-tuned model with my own dataset and task?

### ISSUE THREAD

**Issue by blurLake** [salesforce/CodeT5#32]
Hi, 

I fine-tuned a model using my own dataset, task and subtask. Say the task is called "own_task" and subtask is "c" since it is about c scripts. Now I have models saved in saved_models/own_task/c/codet5_small/checkpoint-best-ppl/  and checkpoint-last/ as pytorch_model.bin. Then I try to load this model using 
```
from transformers import T5Config, RobertaTokenizer, T5ForConditionalGeneration
model = T5ForConditionalGeneration.from_pretrained("dir_saved_model")
```

It fails with error about missing config.json file. Is this the correct way to load the model? Do I need to generate a config.json for the model manually, or it can be done automatically?

Thank you very much.

**Comment by yuewang-cuhk** [comment]
Hi, if the model folder does not contain `config.json`, you load the model via
```
from transformers import T5Config, RobertaTokenizer, T5ForConditionalGeneration
config = T5Config.from_pretrained('Salesforce/codet5-small')
model = T5ForConditionalGeneration.from_pretrained("dir_saved_model",  config=config)
```
Or you can revise the way you save the model in `run_gen.py` [here](https://github.com/salesforce/CodeT5/blob/34a6310f9604f77031b6a412a1b2b3873dbd6e19/run_gen.py#L340) like this: `model.save_pretrained(output_model_file)`. Then the `output_model_file` will contain `config.json`.
