### ISSUE TITLE
Script for finetuning refine task ?

### ISSUE THREAD

**Issue by Rishov-NightKING** [salesforce/CodeT5#33]
Hi, 
I would try to finetune different dataset on refine task. But I cant seem to find the script for refinement task.

It will help me a lot if you enlighten me up.

Thanks in advance.

**Comment by yuewang-cuhk** [comment]
Hi, the fine-tuning script for all generation task is [run_gen.py](https://github.com/salesforce/CodeT5/blob/main/run_gen.py). Please refer to [here](https://github.com/salesforce/CodeT5#how-to-fine-tune-on-your-own-task-and-dataset) for how to fine-tune on different datasets. Thanks.
