### ISSUE TITLE
How to use a fine-tuned Checkpoint?

### ISSUE THREAD

**Issue by KareemAlaa2001** [salesforce/CodeT5#34]
Hi,

This might seem like a basic question, but I want to be sure I'm on the right track here. I am trying to use the code generation fine-tuned checkpoint, but since the binary file isn't sufficient to load the model in huggingface, I downloaded the [huggingface codet5-base directory ](https://huggingface.co/Salesforce/codet5-base/tree/main) and replaced the pythorch_model.bin with the binary file corresponding to the concode task. Is this the correct way to go about this?

**Comment by yuewang-cuhk** [comment]
Yes, this is one correct way. Or you can follow another way [here](https://github.com/salesforce/CodeT5/issues/32#issuecomment-1053954801)

**Comment by KareemAlaa2001** [comment]
Cool, thanks for weighing in!
