### ISSUE TITLE
Use the python code generation example in the paper

### ISSUE THREAD

**Issue by zhengzhongliang** [salesforce/CodeT5#36]
Hi,
I was trying to find the model to fulfill the example in the paper "Generate Python: increment value" -> "def inc_value(x):...".

May I know if there is a released model to do this (no need to fine-tune)? In the readme file the only text-to-code generation model seems to be the concode model, which generates Java code. 

If there is not, may I know what is the recommended model to do the fine-tuning to fulfill this task?

Thanks!

**Comment by yuewang-cuhk** [comment]
Hi, currently there is no released model to do this. You can directly fine-tune the released CodeT5-small/base model on the python subset of CodeSearchNet data for a text-to-code generation task.
