### ISSUE TITLE
The dual-gen pre-trained model

### ISSUE THREAD

**Issue by Vladimir-Chan** [salesforce/CodeT5#37]
Hi,
I'm fine-tuning the CodeT5 model on my dataset for the code generation task. In the paper the CodeT5-base model with the dual-gen achieved the best performance but there are no model with dual-gen released. So,
is the CodeT5-base model released in [hugginface](https://huggingface.co/) the model with the dual-gen?
If not, could you please release the pre-trained model with the dual-gen?

**Comment by yuewang-cuhk** [comment]
Hi, currently we do not released the checkpoints with dual-gen. Tentatively you can directly fine-tune from the released CodeT5-base checkpoint.
