### ISSUE TITLE
unable to regenerate output 

### ISSUE THREAD

**Issue by Pked01** [salesforce/CodeT5#39]
Hi
Thanks for sharing such useful models 
I am trying regenerate the output as shared by you in the gif 
as per gif
the input is `//convert one currency to another`
for generating the output I use code-t5-base model from hugging face and replaced the binary file with concode_codet5_base(from finetune models)
But if you check output below its lot different from what is there in the gif
![image](https://user-images.githubusercontent.com/8408124/158749411-90773fd0-8981-47b3-953c-7dbaf6373768.png)

My question are:
1. Is my approach correct to run the model?
2. If what should be the recommended setting to get the correct output for text to code generation

**Comment by yuewang-cuhk** [comment]
Hi, the model behind the GIF is a CodeT5 checkpoint fine-tuned on our internal Apex data for a text-to-code generation task. Currently the released text-to-code checkpoint is specifically for the Concode dataset and there is no released models for generic text-to-code generation. You are recommended to fine-tune such model on your domain datasets using the CodeT5 pretrained models.
