### ISSUE TITLE
how can i output embedding for code 

### ISSUE THREAD

**Issue by XiaoXiaoYi123** [salesforce/CodeT5#48]

**Comment by yuewang-cuhk** [comment]
Hi, currently we do not test which is the best way for code embedding. We would suggest that you can directly employ the last decoder hidden state or the max/avg pool of all decoder states as the code embedding.

**Comment by trivikramak** [comment]
Hi, 
Is there any update on evaluating good embeddings of code?
Can you suggest the best possible embedding that could be used to cluster a large number of code-snippets to identify common defects among them?
