### ISSUE TITLE
Do you plan to release code for pretraining?

### ISSUE THREAD

**Issue by subercui** [salesforce/CodeT5#50]
Hi, do you plan to release code for pretraining? Or maybe you have already released it, not sure which file to look at.

**Comment by rdurelli** [comment]
I would like to get involved in this too :D

**Comment by yuewang-cuhk** [comment]
Hi, we do not plan to release the pretraining code (duplicated as[ issue 40](https://github.com/salesforce/CodeT5/issues/40)). We'd be happy to anwser the questions regarding its implementation details.

**Comment by redthing1** [comment]
> Hi, do you plan to release code for pretraining? Or maybe you have already released it, not sure which file to look at.

It sucks that they are so adamant to not release the code, who knows what their reasons are. 
Anyway, CodeT5 is not such a great model anyway, I personally would recommend you look at [CodeGen](https://github.com/salesforce/CodeGen), a very recent model that is much, much more powerful than CodeT5 (in our testing, even the smallest codegen model drastically outperformed CodeT5 for tasks such as code completion and summarization). Also CodeT5 models were only 220M (I think) at max, but CodeGen models go from 350M, 2.7B, 6B, and 16B. And that actually has significantly more code release.
