### ISSUE TITLE
Please tell me about "+ dual-gen" and "+ multi-task".

### ISSUE THREAD

**Issue by yfnskw** [salesforce/CodeT5#53]
Hello.
Please forgive me because I am not used to reading papers.
I have a question about the description of the Code T5 paper.
Tables 2 and 4 of the CodeT5 paper have the descriptions "CodeT5-base", "+ dual-gen", and "multi-task".
Does this fit the following interpretation?
"CodeT5-base"
"CodeT5-base + dual-gen"
"CodeT5-base + dual-gen + multi-task"

And is only "Code T5-base" published on Hugging Face?

**Comment by yuewang-cuhk** [comment]
Hi, most of your interpretation are correct except that for "CodeT5-base + multi-task", it does not include the dual-gen pretraining objective.
