### ISSUE TITLE
Code for normalizing variables

### ISSUE THREAD

**Issue by pranavsb** [salesforce/CodeT5#58]
Hi,

I am trying to reproduce refine task on my data. I see that dataset for `refine` has abstracted the types and variables eg
```java
private void METHOD_1 ( java.lang.Class VAR_1 )...
```

Is the code to do this provided in `utils.py`? If not, how to go about this?

**Comment by pranavsb** [comment]
Looks like the tool used is [src2abs](https://github.com/micheletufano/src2abs)

**Comment by yuewang-cuhk** [comment]
Hi, sorry for the slow reply.  For this dataset, we directly employ the version from the CodeBERT repo [here](https://github.com/microsoft/CodeBERT/blob/master/GraphCodeBERT/refinement/data.zip).
