### ISSUE TITLE
How to get embedding for javascript and python code snippet?

### ISSUE THREAD

**Issue by smith-co** [salesforce/CodeT5#62]
I have a couple of questions:

a) How can I use CodeT5 to extract embedding for JavaScript and Python code?
b) Can I feed incomplete code JavaScript and Python snippet to extract embedding? Or the code snippet needs to be complete?
c) Have anyone used CodeT5 to perform code to code search?

**Comment by yuewang-cuhk** [comment]
Hi, for embedding exaction with CodeT5, we encourage to follow the BART manner by feeding the sequences to both encoder and decoder. Then you can employ either the last decoder state or the average pooling of all decoder states as the sequence embedding. 

For code search, we did not try it yet. You can refer to this [UniXcoder](https://arxiv.org/pdf/2203.03850.pdf) paper which includes such evaluation for the moment.

**Comment by TejaswiniiB** [comment]
Hi @yuewang-cuhk 
Does code-t5 give proper embeddings for python code with multiple methods as well? Or only for the code with single method?

**Comment by yuewang-cuhk** [comment]
HI TejaswiniiB, we did not test it but believe it should give proper embeddings.
