### ISSUE TITLE
Clone detection for python code snippets?

### ISSUE THREAD

**Issue by TejaswiniiB** [salesforce/CodeT5#63]
Hi, 
Can we do clone detection on python codes also using clone task? Description in the README mentioned clone detection on Java Data specifically. 
But after looking at the code in `run_clone.py` etc, looks like same clone task can be used for clone detection of python codes also, since the internal models being used are same for any task. Am I correct?

**Comment by yuewang-cuhk** [comment]
Hi, yes, you can finetune CodeT5 models on clone detection with Python code, as their pretraining dataset includes Python language.
