### ISSUE TITLE
What does the get_model_size() function mean?

### ISSUE THREAD

**Issue by leemgs** [salesforce/CodeT5#65]
I thought that the execution result of get_model_size() was the amount of memory required for the model to be loaded into memory.
The current execution result of the `get_model_siz()` function was just like `model.num_parameters()`.

So I wonder what the meaning and intent of the get_model_size() function are.
Do you want to print the number of parameters?
Or,  do you want to print the size of the model loaded into memory?

* https://github.com/salesforce/CodeT5/blob/main/models.py#L17
```bash
def get_model_size(model):
    model_parameters = filter(lambda p: p.requires_grad, model.parameters())
    model_size = sum([np.prod(p.size()) for p in model_parameters])
    return "{}M".format(round(model_size / 1e+6))
```

* codeT5-base model:  pytorch_model.bin (892MB)
  * https://huggingface.co/Salesforce/codet5-base/tree/main
![image](https://user-images.githubusercontent.com/82404/184792602-d87324ba-c97d-4269-86b7-405aabd48474.png)

**Comment by yuewang-cuhk** [comment]
Hi, it is the same as `model.num_parameters()`.
