### ISSUE TITLE
Not a mach.so file

### ISSUE THREAD

**Issue by mirzayaser3** [salesforce/CodeT5#67]
I am trying to execute the concode part `python3.7 run_exp.py --model_tag codet5_base --task concode --sub_task none`.

Cant this code be executed on MacOS? I am getting this error 
`OSError: dlopen(/my-languages.so, 0x0006): tried: 'my-languages.so' (not a mach-o file)`

Did this error occur previously? If yes, can you please navigate me on how to overcome this?

**Comment by kiran-kate** [comment]
@mirzayaser3, did you find an alternative to using the .so?
