### ISSUE TITLE
Generation task (SysML)

### ISSUE THREAD

**Issue by mirzayaser3** [salesforce/CodeT5#68]
I want to create my own dataset for the generation task. I want to convert text to SySML code.
The SysML code examples are here (https://github.com/Systems-Modeling/SysML-v2-Release/tree/master/sysml/src/examples).

In the data/concode folder I want to give my own dev, test, and train.json files. But the thing is will I be able to generate SysML code? Is the current codeT5 compatible with my task?
I am starting to research this code. Any suggestions or ideas are appreciable.
Thanks.

**Comment by yuewang-cuhk** [comment]
Hi there, please follow [here](https://github.com/salesforce/CodeT5#how-to-fine-tune-on-your-own-task-and-dataset) to finetune CodeT5 on the customized dataset. You would be suggested to create a new task for it.
