### ISSUE TITLE
Multi-task training scripts?

### ISSUE THREAD

**Issue by Guitaricet** [salesforce/CodeT5#7]
Hi! In the paper you mention multi-task setup, but I can't find anything related to it in the code.

Have you released it? If not, what are your plans for it?

**UPD:** What is the command for code generation fine-tuning? `run_exp.py` only has these tasks `'summarize', 'concode', 'translate', 'refine', 'defect', 'clone'`

**Comment by yuewang-cuhk** [comment]
Hi @Guitaricet,`concode` is the command for code generation. We plan to release the multi-task fine-tuning scripts soon.
