### ISSUE TITLE
The training hyper-parameters for Reproducing Code Generation

### ISSUE THREAD

**Issue by xguo7** [salesforce/CodeT5#78]
Hello,

I tried to follow the instructions to fine-tune the code generation task in Concode dataset, but failed to get the similar results as shown in the paper. What I got is: Bleu: 26.88, EM: 21.30.

Could you provide all the hyper-parameters regarding the fine-tuning on Concorde datasets?
Thank you!

**Comment by yuewang-cuhk** [comment]
Hi, we have released the training hyper-parameters in the [run_exp.py](https://github.com/salesforce/CodeT5/blob/main/sh/run_exp.py). From your results, the BLEU score is much lower than expected and is problematic. To reproduce the results, please use our released finetuned checkpoints [here](https://github.com/salesforce/CodeT5#download).
