### ISSUE TITLE
CodeBLEU

### ISSUE THREAD

**Issue by Debdeep1998** [salesforce/CodeT5#79]
Does CodeBLEU  work on generated snippets where the generated code isn't compilable? And if not then how is CodeBLEU used in evaluating CodeT5 model if the generated code by the model might not have an AST.

**Comment by yuewang-cuhk** [comment]
Hi, from our experience in using CodeBLEU, it can still give reasonable scores when the code is not compilable. For details of how CodeBLEU is computed, please refer to the original [paper](https://arxiv.org/abs/2009.10297) and we would suggest to ask the original authors for these questions.
