### ISSUE TITLE
Prompt for code summarization using AutoModelForSeq2SeqLM of HuggingFace

### ISSUE THREAD

**Issue by Runingtime** [salesforce/CodeT5#92]
Hi,

May I ask what prefix or suffix to use for code summarization when using AutoModelForSeq2SeqLM of HuggingFace?

**Comment by yuewang-cuhk** [comment]
Hi there, for code summarization, we suggest to use this CodeT5-base [checkpoint](https://huggingface.co/Salesforce/codet5-base-multi-sum) that is pretrained in code summarization across 6 PLs from CodeSearchNet in a multi-task setting. No prefix is required for this checkpoint.
